### PR TITLE
Update feedstock with v4.0.1rc2

### PR DESCRIPTION
**Pull request by abravalheri**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)

This PR also brings the latest changes on the feedstock's master, as recommended in #35

### CODE REVIEW

**Review by maresb — APPROVED** [review]
Looks great to me!!! I recommend merging.

**Comment by maresb** [comment]
Err, wait...

**Comment by maresb** [comment]
Don't merge yet! There's something missing...

**Comment by maresb** [comment]
No, sorry, all good!

I thought [this](https://github.com/abravalheri/pyscaffold-feedstock/blob/rc/recipe/conda_build_config.yaml) was missing, but it's actually in the separate `recipe/conda_build_config.yaml` file. (This file importantly prevents the build from being published with the `main` label.)

Sorry for the noise, go ahead and merge!

**Comment by abravalheri** [comment]
Thank you very much for the review @maresb

**Comment by maresb** [comment]
Hmm, I don't understand why it's not showing up. It should have been uploaded a long time ago.
https://anaconda.org/conda-forge/pyscaffold/files

For `rc1` I accidentally uploaded to the `main` label because I didn't know about `conda_build_config.yaml`. Then chrisburr changed the label for me by hand. The point is, I have not yet succeeded in creating a release candidate by myself. But I expected this PR to succeed.

I'd recommend reading over https://conda-forge.org/docs/maintainer/knowledge_base.html#pre-release-builds to see if I missed anything obvious, and if not, then asking on [Gitter](https://gitter.im/conda-forge/conda-forge.github.io).

**Comment by abravalheri** [comment]
The documentation says that a "rerender needs to happen for these changes to reflect in CI files" when talking about `recipe/conda_build_config.yaml`. I was supposing that previously there was a rerender because the file was already changed before the PR, but maybe those things got a bit out of sync... I suppose we could try a new rerender?

@conda-forge-admin please rerender

**Comment by maresb** [comment]
@abravalheri very good idea!!! You may need to make an empty commit, reopen the pull request, and then the rerender command should work.

**Comment by abravalheri** [comment]
Well, I tried to rerender localy using [conda-smithy](https://conda-forge.org/docs/maintainer/updating_pkgs.html#dev-rerender-local) but it did not work, so I guess I have to ask on Gitter :P

**Comment by maresb** [comment]
That's brutal. No acknowledgement. :disappointed:

**Pull request merged**
