### PR TITLE
Attempt to publish v4.0.1rc2 again

### PR DESCRIPTION
**Pull request by abravalheri**
Checklist
* [x ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)

As reported in #38, after the previous PR was merged, the packaged did not end up published in Anaconda.

This empty PR is an another attempt...

No files were changed.

### CODE REVIEW

**Comment by abravalheri** [comment]
@conda-forge-admin please rerender

**Comment by maresb** [comment]
I just had an idea. Maybe something is messed up with the build numbers (perhaps due to Chris relabeling `rc1` from `main` to `pyscaffold_rc`). Let's try bumping the build number.

**Comment by abravalheri** [comment]
Sorry @maresb, I just clicked the merge button a few seconds before receiving your message 😅 

It seems that some sort of CI is running right now on the merge commit on the RC branch, which I didn't see happening last time. 🤞 

If it does not work, I will try your suggestion.

**Comment by abravalheri** [comment]
Looks like it worked: https://anaconda.org/conda-forge/pyscaffold/files

😅

**Comment by maresb** [comment]
I hit submit the same instant you closed the PR. :laughing: 

I thought of bumping the build number while writing a call for help to Filipe and Chris... If my suggestion doesn't work, I'll repost the following summary and @-tag them in it.

> We are trying to publish a release candidate, `rc2`. We followed the [knowledge base instructions](https://conda-forge.org/docs/maintainer/knowledge_base.html#pre-release-builds), but nothing is showing up [on anaconda.org](https://anaconda.org/conda-forge/pyscaffold/files). Anderson [asked for help on Gitter](https://gitter.im/conda-forge/conda-forge.github.io?at=604cf4ebe5f1d949d498a549) but unfortunately received no response. More info about our previous attempt can be found in #38.
>
> The `rc1` on anaconda.org was relabeled by Chris after I mistakenly published it with the `main` label, so we have not yet successfully built a package from this `rc` branch.
>
> If you could find the time to take a look, we would really appreciate it!

**Comment by maresb** [comment]
We are really great with synchronized posting!!! :laughing: 

Wow!!! I don't understand why it succeeded though. It seems like it needed the rerender to take place, even if rerendering was a do-nothing operation?

**Comment by abravalheri** [comment]
Thank you very much for all the help @maresb.

I think no software resists to the good'old "have you tried to turn it off and on again?"...

My guess was that the CI process for the previous merge was never triggered... who knows why?
Maybe the CI was too busy, maybe it was due to the fact the `rc` branch did not had me listed as maintainer in the `meta.yaml` yet (the rebase with master was applied in the same PR) so it got confused... Hard to tell

**Comment by maresb** [comment]
In any case, excellent work @abravalheri! That was really tricky, and I'm glad you finally got it working.

**Pull request merged**
